[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Infos"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;Essentiel"
newsButton = "Ressources"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
settingsButton = "PARAMÈTRES"
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "SE CONNECTER"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Le nom d'utilisateur doit être composé de lettres anglaises et peut contenir des chiffres et des tirets du bas. De 4 à 16 caractères."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Créer un compte"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Sélection du serveur"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajouter de nouveaux comptes ou gérer les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Compte standard"
addMojangAccount = "+ Ajouter un compte"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options liées au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus du jeu détaché du launcher."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le launcher fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver des mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods externes (Drop-in)"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour rafraîchir)"
shaderpacks = "Shaders"
shaderpackDesc = "Activer ou désactiver les shaders. Attention, les shaders ne fonctionnent de manière stable que sur des machines performantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un shader"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer les paramètres Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "Maximum de RAM"
minRAM = "Minimum de RAM"
memoryDesc = "Le minimum de RAM recommandé est de 3 Go. Définir les valeurs minimum et maximum à l'identique peut réduire les lags."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner le fichier Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est vérifié avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Paramètres JVM supplémentaires"
jvmOptsDesc = "Paramètres fournis à la JVM lors de l'exécution. N'incluez pas <em>-Xms</em> et <em>-Xmx</em>."
launcherTabHeaderText = "Paramètres du Launcher"
launcherTabHeaderDesc = "Paramètres liés au launcher lui-même."
allowPrereleaseTitle = "Autoriser les mises à jour pré-publiées (Pre-Release)."
allowPrereleaseDesc = "Les pré-versions incluent de nouvelles fonctionnalités qui peuvent ne pas être suffisamment testées ou intégrées.<br>Cela sera toujours vrai si vous utilisez une pré-version."
dataDirectoryTitle = "Répertoire des données"
selectDataDirectory = "Sélectionner le répertoire des données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés dans le répertoire des données.<br>Les captures d'écran et les mondes sauvegardés sont enregistrés dans le dossier de configuration du serveur."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Consulter les informations et les notes de mise à jour pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Code source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de mise à jour"
changelog = "Historique des modifications"
noReleaseNotes = "Aucune note de mise à jour"
viewReleaseNotes = "Voir les notes sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du Launcher"
launcherUpdatesHeaderDesc = "Télécharger, installer et vérifier les mises à jour du launcher."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Quoi de neuf"
updateReleaseNotes = "Notes de mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "SE CONNECTER"
loggingIn = "CONNEXION..."
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Champ requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Consultez la console (CTRL + Shift + i) pour plus de détails."
okay = "Continuer"
serverUnavailableTitle = "Serveurs indisponibles"
serverUnavailableDesc = "Les serveurs sont indisponibles, nous allons essayer de lancer la version téléchargée. Si elle ne se lance pas, vérifie ta connexion internet et redémarre l'application."
serverUnavailableOkay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement.."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Vérification des informations système.."
noCompatibleJava = "Aucune installation Java<br>compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une version 64 bits de Java {major}. Voulez-vous l'installer ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java.."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Consultez la console (CTRL + Shift + i) pour plus de détails."
javaRequired = "Java est requis<br>pour le lancement"
javaRequiredMessage = "Une installation valide x64 de Java {major} est requise pour le lancement.<br><br>Consultez le <a href=\"https://envel-experimental.github.io/Site/java.html\">guide d'installation de Java</a> pour les instructions."
javaRequiredDismiss = "Compris"
javaRequiredCancel = "Retourner en arrière"

[js.landing.downloadJava]
findJdkFailure = "Impossible de trouver la distribution OpenJDK."
javaDownloadCorruptedError = "La distribution JDK téléchargée a un hachage invalide, le fichier est peut-être corrompu."
extractingJava = "Extraction de Java"
javaInstalled = "Java est installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des informations du serveur.."
fatalError = "Erreur fatale"
unableToLoadDistributionIndex = "Impossible de charger les fichiers depuis nos serveurs. Réessayez ou vérifiez votre connexion Internet."
pleaseWait = "Veuillez patienter.."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Réessayez. Consultez la console (CTRL + Shift + i) pour plus de détails."
validatingFileIntegrity = "Vérification de l'intégrité des fichiers.."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers.."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation du lancement.."
launchingGame = "Lancement du jeu.."
launchWrapperNotDownloaded = "Le fichier principal, LaunchWrapper, n'a pas pu être téléchargé correctement. En conséquence, le jeu ne peut pas se lancer.<br><br>Pour résoudre ce problème, désactivez temporairement votre logiciel antivirus et relancez le jeu.<br><br>Si vous avez le temps, veuillez <a href=\"https://github.com/Envel-Experimental/HeliosLauncher/issues\">signaler ce problème</a> et indiquer quel antivirus vous utilisez. Nous les contacterons pour essayer de résoudre le problème."
doneEnjoyServer = "Terminé. Lancement en cours..."
checkConsoleForDetails = "Veuillez consulter la console (CTRL + Shift + i) pour plus de détails."
launchingOffline = "Lancement de la copie hors ligne. Erreur des serveurs."

[js.landing.news]
checking = "Vérification des actualités"

[js.landing.discord]
loading = "Chargement du jeu.."
joining = "En route pour Westeros !"
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Fichiers exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Un problème est survenu"
errorMessage = "Erreur d'authentification Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Un problème est survenu"
errorMessage = "Erreur de déconnexion de votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Sélectionner un compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Avertissement<br>C'est votre dernier compte"
lastAccountWarningMessage = "Pour utiliser le launcher, vous devez être connecté à au moins un compte. Vous devrez vous reconnecter après votre déconnexion.<br><br>Êtes-vous sûr de vouloir vous déconnecter ?"
confirmButton = "Je suis sûr"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d'utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner un compte"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Supprimer"
deleteFailedTitle = "Erreur de suppression<br>Du mod Drop-in {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n'est pas utilisé et réessayez."
failedToggleTitle = "Erreur lors du basculement<br>d'un ou plusieurs mods Drop-in"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Pré-version"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de mise à jour."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle pré-version disponible"
downloadingButton = "Téléchargement.."
downloadButton = "Télécharger depuis GitHub<span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Fermez le launcher et lancez le dmg pour mettre à jour.</span>"
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Vérifier les mises à jour"
checkingForUpdatesButton = "Vérification des mises à jour.."

[js.settings.msftLogin]
errorTitle = "Erreur de connexion Microsoft"
errorMessage = "Impossible d'authentifier votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur critique : serveurs indisponibles"
fatalErrorMessage = "Impossible d'établir une connexion avec nos serveurs.<br><br>Assurez-vous d'avoir une connexion internet et redémarrez l'application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Impossible de rafraîchir la connexion"
failedMessage = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Impossible de rafraîchir la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Se connecter"
selectAnotherAccountButton = "Sélectionner un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Vérification des mises à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Vérifier les mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n'est pas encore configuré pour Minecraft. Si vous avez récemment acheté le jeu ou l'avez obtenu via le Xbox Game Pass, configurez votre profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n'avez pas encore acheté le jeu, vous pouvez le faire sur <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Votre compte Microsoft n'a pas de compte Xbox associé."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live indisponible"
xblBannedDesc = "Votre compte Microsoft a été créé dans un pays où Xbox Live est indisponible ou bloqué."
under18Title = "Erreur de connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes d'utilisateurs de moins de 18 ans doivent être ajoutés à un « Groupe familial » par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Veuillez signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point de terminaison d'authentification n'a pas été trouvé. Veuillez signaler ce problème."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez tenté de vous connecter avec un compte migré. Essayez de nouveau en utilisant l'adresse e-mail du compte comme nom d'utilisateur."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L'adresse e-mail ou le mot de passe que vous avez saisi est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Il y a eu trop de tentatives de connexion à ce compte récemment. Veuillez réessayer plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d'accès fourni n'est pas valide."
tokenHasProfileTitle = "Erreur de connexion :<br>Le jeton a déjà un profil"
tokenHasProfileDesc = "Le jeton d'accès est déjà lié à un profil. Le choix des profils n'est pas encore implémenté."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Le nom d'utilisateur/mot de passe n'est pas renseigné ou le mot de passe contient moins de 3 caractères."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de données non pris en charge"
unsupportedMediaTypeDesc = "Type de données non pris en charge. Veuillez signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Le compte a été migré vers un compte Microsoft. Veuillez vous connecter via Microsoft."
unreachableTitle = "Erreur de connexion :<br>Serveur indisponible"
unreachableDesc = "Impossible de se connecter aux serveurs d'authentification. Assurez-vous qu'ils fonctionnent et que vous êtes connecté à internet."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Le compte avec lequel vous essayez de vous connecter n'a pas de copie achetée de Minecraft. Vous pouvez l'acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.processbuilder.exit]
exitErrorHeader = "ERREUR DU JEU. SI CELA SE REPRODUIT, CONTACTEZ LE SUPPORT."
message = "Le jeu s'est terminé avec le code d'erreur : "

[js.processbuilder.exit.crash]
title = "Oups, quelque chose s'est mal passé"
body = "Une erreur s'est produite avec le code {exitCode}.<br><br>Essaie de désactiver ton antivirus et de redémarrer le programme en tant qu'administrateur. Si cela ne t'aide pas, contacte le support.<br><br>Parfois, la désactivation de l'optimisation aide."
close = "Fermer"
disable = "Désactiver l'optimisation"

[js.processbuilder.exit.disabled]
title = "Optimisation désactivée"
body = "Nous avons désactivé l'optimisation. Tu peux toujours remettre les modifications dans les paramètres. Essaie de relancer le jeu."
close = "Fermer"

[js.processbuilder.crash]
title = "Plantage du jeu"
body = "Un problème potentiel a été détecté et nous pouvons le corriger automatiquement : {description}"
close = "Fermer"
fix = "Corriger et redémarrer"

[js.systemChecks]
warningTitle = "Problèmes techniques"
lowTotalRAM = "La quantité de mémoire vive (RAM) de ton ordinateur est inférieure à 6 Go. Nous ne pouvons pas garantir le fonctionnement du launcher sur cet ordinateur, car il est inférieur à la configuration minimale requise."
lowFreeRAM = "Il semble qu'il n'y ait pas assez de mémoire vive (RAM) disponible sur ton ordinateur. Essaie de fermer les programmes inutiles. Nous ne pouvons pas garantir que le jeu fonctionnera de manière stable."
lowDiskSpace = "Il semble que tu aies trop peu d'espace sur ton disque principal et que le jeu ne puisse pas s'installer par manque de stockage. Il est nécessaire de libérer de l'espace sur ton disque principal."

[js.uicore.update]
updateAvailableTitle = "Mise à jour disponible"
updateAvailableDesc = "Une nouvelle mise à jour est disponible. L'installer maintenant ?"
updateButton = "Mettre à jour"
updateFromSiteButton = "Mettre à jour depuis le site"
laterButton = "Plus tard"